# Welcome to Jekyll!
#
# This config file (_congig.yml) is meant for settings that affect your whole blog,
# values which you are expected to set up once and rarely edit after that. If you 
# find yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Rikki J Prince (author)"
email: me@rikkijprince.com
description: >- # this means to ignore newlines until "baseurl:"
  Books by Rikki J Prince
  The Sarah Mackay saga
  RJP readers for English learners (A1, A2, B1, B2, C1, C2)
  Philosophical essays
  Speculative fiction
  The occult - a scientific perspective
  The art & science of pleasure
  The art & science of risk
baseurl: "" # leave empty for the root site of rikkijprince.github.io
url: "https://rikkijprince.com" # the base hostname & protocol for your site
twitter_username: rikkijprince
github_username:  rikkijprince

# Build settings
theme: minimal-mistakes-jekyll

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  
# Navigation menu
header_pages:
  - index.md
  - about.md
  - novels.md
  - stories.md
  - experimental.md
  - zanzibar.md
  - readers.md
  - contact.md

# Optional navigation bar (for layout customization)
nav:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
  - title: "Novels"
    url: /novels/
  - title: "Short Stories"
    url: /stories/
  - title: "Experimental Works"
    url: /experimental/
  - title: "Zanzibar"
    url: /zanzibar/
  - title: "RJP Readers"
    url: /readers/
  - title: "Contact Info"
    url: /contact/

sass:
  style: compressed

    
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
